version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.pem:/etc/nginx/server.pem
      - ./server.crt:/etc/nginx/server.crt
  quarkus:
    image: quarkus/mtls_demo
    depends_on:
      - nginx
